In [11]:
#dolittle decomposition algorithm

A = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

n = A.shape[0]
    
U = np.zeros((n, n))
L = np.eye(n)


for i in range(n):
        
    U[i, i:] = A[i, i:] - L[i,:i] @ U[:i,i:]
    L[(i+1):,i] = (A[(i+1):,i] - L[(i+1):,:] @ U[:,i]) / U[i, i]
    

print("Matrix A")
print(A)
print("Matrix U")
print(U)
print("Matrix L")
print(L)

#To Check
NewA = L@U
print("Matrik LU")
print(NewA)



Matrix A
[[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]
Matrix U
[[ 1. -2.  3.]
 [ 0. -3.  6.]
 [ 0.  0.  0.]]
Matrix L
[[ 1.  0.  0.]
 [-4.  1.  0.]
 [ 7. -2.  1.]]
Matrik LU
[[ 1. -2.  3.]
 [-4.  5. -6.]
 [ 7. -8.  9.]]


In [19]:
import numpy as np

A = np.array([[5, -2, 3], [-4, 5, -6], [7, -8, 9]])

n = A.shape[0]
m = A.shape[1]

A2 = []


for i in range (0,n):
    for k in range(0,m):
        A2.append(abs(A[i,k]**2))

for i in range (1,n*n):
    SumA = A2[0]+A2[i]
    A2[0] = SumA


#Euclidean norm  
EN = np.sqrt(SumA)
print("Euclidean norm =", EN)



Euclidean norm = 17.578395831246947


In [9]:
import numpy as np

A = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

n = A.shape[0]
m = A.shape[1]

ListARow = []


for i in range (0,n):
    SumARow = 0
    for k in range(0,m):
        SumARow += abs(A[i,k])

    ListARow.append(SumARow)

#Infinity norm
IN = max(ListARow)
print("Infinity norm = ", IN)



3
Infinity norm =  24


In [4]:
import numpy as np
from scipy.linalg import solve

#Question 2)a) and 2)c)
A = np.array([[4,-1,0,0],[-1,4,-1,0],[0,-1,4,-1],[-1,0,-1,4]])
B = np.array([[-1],[2],[4],[10]])
X = solve(A,B)

print("Verify solution")
print(X)

n=5

xii = np.zeros(B.shape[0])
x = np.array([0,0,0,0])
xo = np.array([0,0,0,0])

print()
print(x)

for k in range(3):
    
    for i in range(n-1):
        
        xi = (((B[i]-np.sum((A[i,(i+1):])*(x[(i+1):]))-np.sum((A[i,:i])*(x[:i]))))/(A[i,i]))
        xii[i] = xi
        
    print(xii)
    x = xii+xo

Verify solution
[[0.]
 [1.]
 [2.]
 [3.]]

1
[0 0 0 0]
[-0.25  0.5   1.    2.5 ]
[-0.125   0.6875  1.75    2.6875]
[-0.078125  0.90625   1.84375   2.90625 ]
