In [209]:
#example lecture note chapter 4
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix
from scipy.linalg import solve

n   = 4
Eqn = []
u   = []
v   = []
X   = []
#Create variables of U i.e. U00 until U44
#u array for all variables from U00 until U44, v array for unknown variable U11,U12,U13,U21,U22,U23,U31,U32,U33

for j in range(0,n+1):
    for i in range(0,n+1):
        u.append(str('U')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            v.append(str('U')+str(j)+str(i))      
        else:
            None
            
u = symbols(u) #initialize variables to insert at linear equation using sympy
U = np.reshape(u, (n+1,n+1)) #reshape to change u in the form of matrix

#boundary condition using value given
for i in range (1,n):
    U[i,0] = 0 # y = 0 boundary (bawah)
    U[i,n] = 100 # y = n boundary (atas)
    U[0,i] = 75 # x = 0 boundary (kiri)
    U[n,i] = 50 # x = n boundary (kanan)

#loop for creating linear simulatanous equation using sympy and insert the equation in array "Eqn"
for i in range(1,n):
    for j in range(1,n):
        eqn = U[i+1,j]+U[i-1,j]+U[i,j+1]+U[i,j-1]-4*U[i,j]
        Eqn.append(eqn)

v = symbols(v) #initialize variables to insert function linear to matrix using sympy
A, b = linear_eq_to_matrix(Eqn, v) #change all the linear equation in the form of matrix

MatA = np.array(A).astype(np.float64) #Change Sympy matrix form to numpy matrix form 
MatB = np.array(b).astype(np.float64) 

x = solve(MatA,MatB) #linalg solve for Ax = B finding the U
X = x.tolist()

print(v, "=", X, "respectively")

[U11, U12, U13, U21, U22, U23, U31, U32, U33] = [[42.85714285714286], [63.16964285714286], [78.57142857142858], [33.25892857142858], [56.25000000000001], [76.11607142857143], [33.92857142857144], [52.45535714285716], [69.64285714285715]] respectively


In [99]:
#tutorial elliptic 1b
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix
from scipy.linalg import solve

n   = 3
Eqn = []
u   = []
v   = []
X   = []

for j in range(0,n+1):
    for i in range(0,n+1):
        u.append(str('U')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            v.append(str('U')+str(j)+str(i))      
        else:
            None
            
u = symbols(u)
U = np.reshape(u, (n+1,n+1)) 

for i in range (1,n):
    U[i,0] = 0 # y = 0 boundary (bawah)
    U[i,n] = 75 # y = n boundary (atas)
    U[0,i] = 50 # x = 0 boundary (kiri)
    U[n,i] = 25 # x = n boundary (kanan)

for i in range(1,n):
    for j in range(1,n):
        eqn = U[i+1,j]+U[i-1,j]+U[i,j+1]+U[i,j-1]-4*U[i,j]
        Eqn.append(eqn)

v = symbols(v) 
A, b = linear_eq_to_matrix(Eqn, v) 

MatA = np.array(A).astype(np.float64) 
MatB = np.array(b).astype(np.float64) 

x = solve(MatA,MatB)
X = x.tolist()

print(v, "=", X, "respectively")

[U11, U12, U21, U22] = [[31.25], [50.0], [25.0], [43.75]] respectively


In [77]:
#tutorial elliptic c over relaxation technique (relax lah sangat)
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix
from scipy.linalg import solve

n   = 3
UII  = []
u   = []
v   = []
X   = []

for j in range(0,n+1):
    for i in range(0,n+1):
        u.append(str('U')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            v.append(str('U')+str(j)+str(i))      
        else:
            None
            
u = symbols(u)
U = np.reshape(u, (n+1,n+1)) 

for i in range (1,n):
    U[i,0] = 0 # y = 0 boundary (bawah)
    U[i,n] = 75 # y = n boundary (atas)
    U[0,i] = 50 # x = 0 boundary (kiri)
    U[n,i] = 25 # x = n boundary (kanan)

for i in range(1,n):
    for j in range(1,n):
        UI = (U[i+1,j]+U[i,j+1]+U[i,j-1]+U[i-1,j])/4
        UII.append(UI)
        

v = symbols(v) 

print(UII)
print()

U1 = lambda U11,U12,U21,U22: U12/4 + U21/4 + 25/2
U2 = lambda U11,U12,U21,U22: U11/4 + U22/4 + 125/4
U3 = lambda U11,U12,U21,U22: U11/4 + U22/4 + 25/4
U4 = lambda U11,U12,U21,U22: U12/4 + U21/4 + 25

U110 = 0
U120 = 0
U210 = 0
U220 = 0 
count = 1

# Reading tolerable error
e = 0.0001

# Reading relaxation factor
w = 1.5

condition = True

while condition:
    U111 = (1-w) * U110 + w * U1(U110,U120,U210,U220)
    U121 = (1-w) * U120 + w * U2(U111,U120,U210,U220)
    U211 = (1-w) * U210 + w * U3(U111,U121,U210,U220)
    U221 = (1-w) * U220 + w * U4(U111,U121,U211,U220)
    print('%d\t%0.4f\t%0.4f\t%0.4f\t%0.4f\n' %(count, U111,U121,U211,U221))
    e1 = abs(U110-U111);
    e2 = abs(U120-U121);
    e3 = abs(U210-U211);
    e4 = abs(U220-U221);
    
    count += 1
    U110 = U111
    U120 = U121
    U210 = U211
    U220 = U221
    
    condition = e1>e and e2>e and e3>e and e4>e

print((U111,U121,U211,U221))

[U12/4 + U21/4 + 25/2, U11/4 + U22/4 + 125/4, U11/4 + U22/4 + 25/4, U12/4 + U21/4 + 25]

1	18.7500	53.9062	16.4062	63.8672

2	35.7422	57.2754	38.5254	41.4917

3	36.8042	47.5983	19.4733	41.9060

4	25.4997	48.3530	24.9155	44.0227

5	33.4758	51.7604	25.9792	44.6410

6	31.1645	49.4218	24.8125	43.0173

7	31.0056	49.9227	24.7274	43.9851

8	31.2410	50.1234	25.2211	43.7616

9	31.3837	49.9928	24.9440	43.7205

10	31.1594	49.9586	24.9830	43.7428

11	31.2734	50.0268	25.0146	43.7691

12	31.2538	49.9952	25.0013	43.7391

13	31.2468	49.9971	24.9941	43.7521

14	31.2483	50.0016	25.0031	43.7507

15	31.2526	50.0004	24.9997	43.7497

16	31.2487	49.9992	24.9996	43.7497

(31.24874021394345, 49.99918837044977, 24.999569840176328, 43.749687384854866)


In [218]:
#Tutorial 4 elliptic 3c
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix
from scipy.linalg import solve

n   = 3
h   = 1/3
Eqn = []
u   = []
f   = []
v   = []
X   = []
xi  = np.zeros(n)
yi  = np.zeros(n) 

def FF(x,y):
    return -2*((np.pi)**2)*(np.sin(x*np.pi))*(np.sin(y*np.pi))

for i in range(1,n):
    xi[i] = i*h     #boundary condition
    yi[i] = i*h     #boundary condition #set then put it in the array

for j in range(0,n+1):
    for i in range(0,n+1):
        u.append(str('U')+str(j)+str(i))
        f.append(str('f')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            v.append(str('U')+str(j)+str(i)) 
        else:
            None
            
u = symbols(u) #initialize variables to insert at linear equation using sympy
f = symbols(f)
U = np.reshape(u, (n+1,n+1)) #reshape to change u in the form of matrix
F = np.reshape(f, (n+1,n+1))

for i in range (1,n):
    for j in range (1,n):
        F[i,j] = FF(xi[i],yi[j])
        

#boundary condition using value given
for i in range (1,n):
    U[i,0] = 0 # y = 0 boundary (bawah)
    U[i,n] = 0 # y = n boundary (atas)
    U[0,i] = 0 # x = 0 boundary (kiri)
    U[n,i] = 0 # x = n boundary (kanan)

#loop for creating linear simulatanous equation using sympy and insert the equation in array "Eqn"
for i in range(1,n):
    for j in range(1,n):
        eqn = U[i+1,j]+U[i-1,j]+U[i,j+1]+U[i,j-1]-4*U[i,j]-(h**2)*F[i,j]
        Eqn.append(eqn)

v = symbols(v) #initialize variables to insert function linear to matrix using sympy
A, b = linear_eq_to_matrix(Eqn, v) #change all the linear equation in the form of matrix

MatA = np.array(A).astype(np.float64) #Change Sympy matrix form to numpy matrix form 
MatB = np.array(b).astype(np.float64) 

x = solve(MatA,MatB) #linalg solve for Ax = B finding the U
X = x.tolist()

print(v, "=", X, "respectively")

[U11, U12, U21, U22] = [[0.8224670334241131], [0.8224670334241131], [0.8224670334241131], [0.8224670334241131]] respectively


In [216]:
#tutorial 4 4b and example chapter 4 parabolic
import numpy as np
from sympy import symbols
from scipy.linalg import solve

N   = 4
n   = N+1
t   = []
ti  = []
X   = np.zeros((n-1,n-1))

K   = 0.835
dx  = 2
dt  = 0.1

for j in range(0,n+1):
    for i in range(0,n+1):
        t.append(str('T')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            ti.append(str('T')+str(j)+str(i)) 
        else:
            None   

t   = symbols(t) 
ti  = symbols(ti)
T   = np.reshape(t, (n+1,n+1)) 
Ti  = np.reshape(ti, (n-1,n-1)) 


for i in range (0,n+1):
    T[i,0] = 0 
    T[i,n] = 50 

for i in range (0,n+1):
    T[0,i] = 100 
    T[n,i] = 50 
    

for j in range(0,n):
    for i in range(1,n):
        T[i,j+1] = T[i,j] + K*(dt/dx**2)*(T[i+1,j]-2*T[i,j]+T[i-1,j])

for j in range(1,n):
    for i in range(1,n):#
        X[i-1,j-1] = T[i,j]

print(T)
print()
print("The matix of")
print()
print(Ti)
print()
print("is equal to")
print()
print(X)
print()
print("Respectively")

[[100 100 100 100 100 100]
 [0 2.0875 4.087846875 6.005588928710938 7.845018111075843
  9.610185081427348]
 [0 0.0 0.0435765625 0.12754587490234376 0.24893300545729985
  0.4049582275016375]
 [0 0.0 0.02178828125 0.0644551830078125 0.12711003369924317
  0.20888234011473641]
 [0 1.04375 2.0439234375 3.002794464355469 3.9225232974139166
  4.805161371700358]
 [50 50 50 50 50 50]]

The matix of

[[T11 T12 T13 T14]
 [T21 T22 T23 T24]
 [T31 T32 T33 T34]
 [T41 T42 T43 T44]]

is equal to

[[2.0875     4.08784688 6.00558893 7.84501811]
 [0.         0.04357656 0.12754587 0.24893301]
 [0.         0.02178828 0.06445518 0.12711003]
 [1.04375    2.04392344 3.00279446 3.9225233 ]]

Respectively


In [276]:
#tutorail 4 5a
import numpy as np
from sympy import symbols
from scipy.linalg import solve

N   = 4
n   = N + 1
t   = []
ti  = []
X   = np.zeros((n-1,n-1))

K   = 0.1
dx  = 0.2
dt  = 0.1

for j in range(0,n+1):
    for i in range(0,n+1):
        t.append(str('T')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            ti.append(str('T')+str(j)+str(i)) 
        else:
            None   

t   = symbols(t) 
ti  = symbols(ti)
T   = np.reshape(t, (n+1,n+1)) 
Ti  = np.reshape(ti, (n-1,n-1)) 

print(T)

for i in range (0,n+1):
    T[i,0] = 70
    T[i,n] = 20

for i in range (0,n+1):
    T[0,i] = 50
    T[n,i] = 20 
    

for j in range(0,n):
    for i in range(1,n):
        T[i,j+1] = T[i,j] + K*(dt/dx**2)*(T[i+1,j]-2*T[i,j]+T[i-1,j])

for j in range(1,n):
    for i in range(1,n):#
        X[i-1,j-1] = T[i,j]
        
#Code below is exist because of the condition given

Tt = np.delete(Ti,(N-1),1)
Xt = np.delete(X,(N-1),1)

print()
print("The matix of")
print()
print(Tt)
print()
print("is equal to")
print()
print(Xt)
print()
print("Respectively")

[[T00 T01 T02 T03 T04 T05]
 [T10 T11 T12 T13 T14 T15]
 [T20 T21 T22 T23 T24 T25]
 [T30 T31 T32 T33 T34 T35]
 [T40 T41 T42 T43 T44 T45]
 [T50 T51 T52 T53 T54 T55]]

The matix of

[[T11 T12 T13]
 [T21 T22 T23]
 [T31 T32 T33]
 [T41 T42 T43]]

is equal to

[[65.      62.5     60.9375 ]
 [70.      68.75    66.71875]
 [70.      66.875   63.4375 ]
 [57.5     51.25    47.34375]]

Respectively


In [6]:
#exam
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix
from scipy.linalg import solve

n   = 3
h   = 1/3
Eqn = []
u   = []
f   = []
v   = []
X   = []
xi  = np.zeros(n)
yi  = np.zeros(n) 

def FF(x,y):
    return 2*x*(x**2+3*y**2-3*y-1)

for i in range(1,n):
    xi[i] = i*h     #boundary condition
    yi[i] = i*h     #boundary condition #set then put it in the array

for j in range(0,n+1):
    for i in range(0,n+1):
        u.append(str('U')+str(j)+str(i))
        f.append(str('f')+str(j)+str(i))
        if   (j >0 and j < (n)) and (i>0 and i<(n)):
            v.append(str('U')+str(j)+str(i)) 
        else:
            None
            
u = symbols(u) #initialize variables to insert at linear equation using sympy
f = symbols(f)
U = np.reshape(u, (n+1,n+1)) #reshape to change u in the form of matrix
F = np.reshape(f, (n+1,n+1))

for i in range (1,n):
    for j in range (1,n):
        F[i,j] = FF(xi[i],yi[j])

print(U)

#boundary condition using value given
for i in range (1,n):
    U[i,0] = 0 # y = 0 boundary (bawah)
    U[i,n] = 0 # y = n boundary (atas)
    U[0,i] = 0 # x = 0 boundary (kiri)
    U[n,i] = 0 # x = n boundary (kanan)

#loop for creating linear simulatanous equation using sympy and insert the equation in array "Eqn"
for i in range(1,n):
    for j in range(1,n):
        eqn = U[i+1,j]+U[i-1,j]+U[i,j+1]+U[i,j-1]-4*U[i,j]-(h**2)*F[i,j]
        print(eqn)
        Eqn.append(eqn)

v = symbols(v) #initialize variables to insert function linear to matrix using sympy
A, b = linear_eq_to_matrix(Eqn, v) #change all the linear equation in the form of matrix

MatA = np.array(A).astype(np.float64) #Change Sympy matrix form to numpy matrix form 
MatB = np.array(b).astype(np.float64) 

print(MatB)
x = solve(MatA,MatB) #linalg solve for Ax = B finding the U
X = x.tolist()

print(v, "=", X, "respectively")

[[U00 U01 U02 U03]
 [U10 U11 U12 U13]
 [U20 U21 U22 U23]
 [U30 U31 U32 U33]]
-4*U11 + U12 + U21 + 0.11522633744856
U11 - 4*U12 + U22 + 0.11522633744856
U11 - 4*U21 + U22 + 0.181069958847737
U12 + U21 - 4*U22 + 0.181069958847737
[[-0.11522634]
 [-0.11522634]
 [-0.18106996]
 [-0.18106996]]
[U11, U12, U21, U22] = [[0.06584362139917695], [0.06584362139917695], [0.0823045267489712], [0.08230452674897118]] respectively
